### ISSUE TITLE
Minimum requirements to run locally

### ISSUE THREAD

**Issue by mbenencase** [FSoft-AI4Code/AgileCoder#10]
Hi, following my other issue, I have two questions:

1. How to run locally? In the README.md I saw that we must configure some environment variables.
2. What are the minimum hardware requirements? RAM memory, GPU VRAM, and so on.

Thanks in advance!

**Comment by minhngh** [comment]
Hi [mbenencase](https://github.com/mbenencase),

Thank you for your questions. Below is our answer:

1. To run on local machines, we install the library and then set some environment variables, as described in Readme.md
    - Install the library:
        ```bash
        pip install agilecoder
        pip install git+https://github.com/tree-sitter/tree-sitter-python.git@master
        ```
    - Set environment variables:
        Because our method uses LLMs like Azure GPTs as backend models, we have to set relevant variables:
        ```bash
        API_KEY=your_api_key
        RESOURCE_ENDPOINT=your_resource_endpoint
        API_TYPE=azure
        API_VERSION=your_api_version
        API_ENGINE=your_api_engine
        ```

2. There are no special requirements to run our library. Our method employs Azure GPTs, so it doesn't require GPUs and consume much RAM or CPU.
