### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '../key.json'

### ISSUE THREAD

**Issue by svanschalkwyk** [FSoft-AI4Code/AgileCoder#4]
/miniconda3/envs/agile_coder/lib/python3.12/site-packages/agilecoder-0.1.4-py3.12.egg/agilecoder/camel/model_backend.py", line 38, in <module>
    json.loads(open("../key.json", "r").read()),
               ^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '../key.json'

**Comment by minhngh** [comment]
Hi [svanschalkwyk](https://github.com/svanschalkwyk),

Thank you for your feedback. This problem can be easily fixed by upgrading *agilecoder* to the latest version.

**Comment by RexTechie** [comment]
I have same problem. Install by source code.
