### ISSUE TITLE
Local run and License

### ISSUE THREAD

**Issue by mbenencase** [FSoft-AI4Code/AgileCoder#9]
Hi, I have two questions:

1. Is it possible to run locally instead on the cloud?
2. What is the license of the software?

**Comment by minhngh** [comment]
Hi [mbenencase](https://github.com/mbenencase),

Thank you for your questions. Below are our answers:

1. Our library can run on both local and cloud machines, but we recommend that you prioritize local machines due to higher performance
2. Our library is released under MIT license
